services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=store_graphql
      - POSTGRES_USER=danmcode
      - POSTGRES_PASSWORD=danmcode
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80


